version: '3'
services:
  grafana:
    image: grafana/grafana:9.4.7
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
  proxy:
    build: yarp-auth-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./appsettings.json:/app/appsettings.json
      