version: '3'
services:
  grafana:
    image: kokuwa/grafana-as-ui-openspace:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
  proxy:
    build: yarp-auth-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./appsettings.json:/app/appsettings.json
      